sprint-3/step-3
Andrei-Borodkin/react-burger pull request #4
Opened 2023-03-19 14:18 UTC by Andrei-Borodkin

2023-03-19 15:52 UTC, andryxxa93 requested changes
Здравствуйте! Хорошая работа 👍 
Что понравилось:
- Роутинг настроен и работает правильно
- Защита приватных и публичных роутов реализована в одном компоненте - так держать
- Добавлены сообщения для пользователя об успешных и не успешных запросах.

Что необходимо исправить:
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов".

- Очень большое количество запросов на получение ингредиентов. Скорее всего где-то есть лишние вызовы функции.

<img width="1440" alt="Снимок экрана 2023-03-19 в 18 33 29" src="https://user-images.githubusercontent.com/60173362/226186806-edb593a6-e34b-4c06-a0a3-9d5e88d3884b.png">

- Невозможно изменить данные в форме на странице профиля - в инпут не вводятся значения. 

- После успешного ресета пароля - вечный лоадер. 
<img width="1440" alt="Снимок экрана 2023-03-19 в 18 37 45" src="https://user-images.githubusercontent.com/60173362/226187057-2a95a317-a90c-4616-8579-53f7f7200878.png">

- Лого обычно делают ссылкой на главную страницу

- Не стоит хранить данные юзера в куках. Необходимо при первом рендере приложения пытаться получить данные с сервера - если в куках есть токен и при первом рендере страницы профиля. 

- Не смог проверить, но скажу на всякий случай, что после обновления токена необходимо повторять запрос в котором пришла ошибка от сервера, но с уже свежим токеном. 

- ProtectedRoute должен использовать  Redirect с параметрами для универсального возращения пользователя обратно туда, куда он хотел попасть.

**Можно лучше**
- На запрос регистрации сервер отвечает токенами, поэтому можно сразу авторизовать юзера.

<img width="650" alt="Снимок экрана 2023-03-19 в 18 36 58" src="https://user-images.githubusercontent.com/60173362/226187014-e0b71797-9b2f-4307-8a03-c06e390046f5.png">

- Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент 
```
{path="/"}:
setCookie('name', value, { path: '/' }).
```
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.

Удачных правок!

2023-03-19 15:52 UTC, andryxxa93 commented on src/services/redux/thunks/thunkRefToken.js
> +                    dispatch(actionSpinner.loading(false))
**Можно лучше**
В этом файле большой кусок кода дублируется несколько раз. Хорошо бы его вынести в отдельную функцию.

2023-03-19 15:52 UTC, andryxxa93 commented on src/services/redux/thunks/thunkReg.js
> +                    toast.success('Пользователь зарегистрирован', { duration: 4000, position: 'top-right', style: { background: 'black', color: 'white', border: '2px solid #4c4cff', fontfamily: 'JetB
**Можно лучше**
Как я могу судить второй параметр в функции `toast.success` чаще всего одинаковый, тогда его лучше вынести в отдельную константу.

2023-03-19 15:52 UTC, andryxxa93 commented on src/components/app/App.js
> +                  <Route path="/login" element={ <ProtectedRouteElement element={<LoginPage />} onlyUnAuth/> } />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-21 07:26 UTC, Andrei-Borodkin commented
поправил активность в шапке
убрал лишние вызовы ингридиента. избавился от повторных рендеров
в профиле сделал инпуты 
убрал вечный лоадер после после смены пароля
лого с ссылкой
убрал данные юзера из куков. получаю их через fetch
рефреш токена  работает .. как в тех задании
после регистрации отправляю на ввод логина (так реализовано в большинстве сайтов .. не стал отходить от традиции)
использую setCookie('name', value, { path: '/' })
toast вынес в функцию
кое что оставил без изменений .. для наглядности

2023-03-21 18:45 UTC, andryxxa93 commented
Супер! Большая часть ошибок исправлены - особенно впечатляет как вы добились кардинального уменьшения количества запросов. 
Однако есть пару проблем, которые необходимо исправить:
- Невозможно изменить данные юзера - не появляется кнопка "Сохранить" . На всякий случай скажу, что необходимо, чтобы пользователь имел возможность изменить какое-то одно поле не заполняя всю форму. 
- Не появляется кнопка "Отмена", которая должна возвращать введенные в форму данные в изначальное состояние.

2023-03-22 07:37 UTC, Andrei-Borodkin commented
При изменение данных в профиле появляются кнопки Сохранить и Отменить. 
При сохранение уходит запрос. Про рефреш токен не забыл. 
При отмене старые данные возвращаются (храню до нажатия сохранить)

2023-03-22 20:03 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-31 16:20 UTC, merged