sprint-5/step-1
Andrei-Borodkin/react-burger pull request #6
Opened 2023-04-19 03:49 UTC by Andrei-Borodkin

sprint-5/step-1

2023-04-19 06:21 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!** 🔥

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть 1 небольшое замечание, которое нужно исправить:**

- Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку. (Компоненты - `forgot-password, reset-password`)

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

- эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

  ```js
  <>
    <div>.....</div>
    <div>.....</div>
  </>
  ```

- Старайтесь, не писать просто циклы внутри компонента, лучше использовать функции, либо `useMemo`;

2023-04-19 06:21 UTC, ArslanMustafin commented on src/components/fedd-stats/FeedStats.tsx
> +        <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-04-19 06:21 UTC, ArslanMustafin commented on src/components/feed-order-detail/FeddOrderDetail.tsx
> +        })
**Можно лучше:**

Тут лучше использовать `useMemo`, а не писать forEach прямо в коде;

2023-04-19 06:21 UTC, ArslanMustafin commented on src/components/feed-order-detail/FeddOrderDetail.tsx
> +                <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-04-19 06:21 UTC, ArslanMustafin commented on src/components/feedCard/FeedCard.tsx
> +            <>
**Можно лучше:**

эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```js
<>
  <div>.....</div>
  <div>.....</div>
</>
```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2023-04-19 06:21 UTC, ArslanMustafin commented on src/components/profileComp/ProfileComp.tsx
> +                        <Button htmlType="button" type="primary" size="small" extraClass="ml-2" onClick={onClickSave}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-04-19 06:21 UTC, ArslanDev666 commented on src/services/redux/socketMiddleware/socketMiddleware.ts
> +        };
**Можно лучше:**

тут ещё можно добавить реконнект при обрыве связи)

2023-04-19 06:21 UTC, ArslanDev666 commented on src/services/redux/socketMiddleware/socketMiddleware.ts
> +        };
**Можно лучше:**

А вот тут можно предусмотреть обновление токена, т.к. у нас есть сокет соединение `/orders`, куда вы передаёте токен.

2023-04-19 15:52 UTC, Andrei-Borodkin commented
где требуется сделал  onSubmit

"эта обёртка <> лишняя" - это все результат рефакторинга .. убрал

обычно ESLint не игнорирую .. но не всегда с ним согласен

src/components/feed-order-detail/FeddOrderDetail.tsx - я стараюсь использовать useMemo .. но тут получилась сложная конструкция .. если вы мне покажете как нужно то буду признателен .. 

src/services/redux/socketMiddleware/socketMiddleware.ts:
я понимаю что для реконнекта нужно что вроде:
        socket.onclose = ev => {
            if (event.code !== 1000) {
                      dispatch(actionWS.socketOnclose());
                      dispatch(actionSpinner.loading(false))
            }
            if (isConnected) {
              reconnectTimer = window.setTimeout(() => {
                 dispatch(actionWS.socketConnect(wsUrl))
              }, 3000)
            }
        };

но проблема возникает с wsUrl я передаю его в компоненте и подключаю socket = new WebSocket(action.payload). 

обновление токена в миделваре видимо нужна при потере соединения с wss://norma.nomoreparties.space/orders?token=... вот только как его отловить ? в socket.onclose = ev => придет ошибка "jwt expired" ?

Если достаточно того что я исправил onSubmit .. то давайте двигаться дальше .. к 6 спринту :)

2023-04-20 06:02 UTC, ArslanDev666 commented
> FeddOrderDetail

https://disk.yandex.com/i/Z7I_UDps_CVj8Q - такс, тут про `useMemo`, там можно спокойно и другие циклы переделать, но думаю вы поймёте суть и сами сможете это сделать.

Не совсем понял какая проблема возникает с wsUrl.

Вы можете всегда проверить что придёт, просто отправив неправильный токен, для этого можно воспользоваться `postman` или аналогичными программами.

По поводу остальных вопросов, их лучше уточнить у наставника)) 

Критических проблем я у вас не заметил, функционал отрабатывает отлично, поэтому да, достаточно.

2023-04-20 06:03 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнем обучении!**

- Все замечания были исправлены;

2023-04-28 05:45 UTC, merged